PRODUCT_SERVICE_NAME: PRODUCT-SERVICE
INVENTORY_SERVICE_NAME: INVENTORY-SERVICE
CART_ORDER_SERVICE_NAME: CART-ORDER-SERVICE
CARD_ORDER_SERVICE_NAME: CART-ORDER-SERVICE
USERS_SERVICE_NAME: USERS-SERVICE
PAYMENT_SERVICE_NAME: PAYMENT-SERVICE
NOTIFICATIONS_SERVICE_NAME: NOTIFICATIONS-SERVICE
AI_SERVICE_NAME: AI-SERVICE