eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/eureka/}

management:
  metrics:
	  tags:
		 application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probe:
      enabled: true
    config:
      enabled: false

logging:
  level:
    root: INFO
  file: 
    name: logs/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} : %msg%n"


PRODUCT_SERVICE_NAME: PRODUCT-SERVICE
INVENTORY_SERVICE_NAME: INVENTORY-SERVICE
CARD_ORDER_SERVICE_NAME: CART-ORDER-SERVICE
