# Run on port 8083 to match Kubernetes routing configs
server.port=8083

# Database configuration
spring.datasource.url=jdbc:mysql://mysql:3306/easybuy_inventory?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=securepassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Production JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Kafka Broker and Serialization Configs
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=inventory-prod-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.properties.spring.json.trusted.packages="*"
spring.kafka.consumer.properties.spring.json.value.default.type=com.substring.easybuy.common.events.PaymentEvent
